### ISSUE TITLE
[BUG] press函数阻塞问题

### ISSUE THREAD

**Issue by MrChen131217** [hyb1996/Auto.js-Pro-Feedbacks#21]
**版本信息**
- Auto.js Pro版本: [7.0.3-6]
- Android版本: [9.0]
- ROM版本: [三星G9550ZCS3DSD5]
- 设备型号: [三星s8+]

**描述Bug**
press函数有几率阻塞

**代码**
press(x,y,1);

**截图或视频**
![1C6EC54C20052E191D45EF7F021E6615](https://user-images.githubusercontent.com/26017411/59036156-55aca200-88a1-11e9-868b-68bfcec51033.png)

**Comment by hyb1996** [comment]
7.0.3-7修复
