### ISSUE TITLE
runtime.loadJar("jsoup.jar");無法使用

### ISSUE THREAD

**Issue by perry86236** [hyb1996/Auto.js-Pro-Feedbacks#28]
**版本信息**
- Auto.js Pro版本: [e.g. 7.0.4.0]
- Android版本: [e.g 8.0]

- 设备型号: [e.g. ASUS zenfone 3 zoom]

**描述Bug**
清楚地描述Bug的信息。

**代码**
runtime.loadJar("jsoup.jar");

**错误日志**
Wrapped com.stardust.pio.UncheckedIOException: java.io.FileNotFoundException: /data/user/0/org.autojs.autojspro/cache/classes/53208f7a68c14aba61c21a85034ac662.dex (/storage/emulated/0/脚本/jsoup/test.js#2)

**截图或视频**
如果有截图或视频，请上传。也可以上传代码文件、项目文件、附近等。

**其他**
可以留下你的QQ，或者其他有用的信息。

**Comment by hyb1996** [comment]
最新pro 8.5.x已经修复了该问题
