### ISSUE TITLE
怎么买Pro

### ISSUE THREAD

**Issue by holleworldabc** [hyb1996/Auto.js-Pro-Feedbacks#32]
**版本信息**
- Auto.js Pro版本: [e.g. 7.0.3-6]
- Android版本: [e.g 7.0]
- ROM版本: [e.g MIUI开发版10.9.5]
- 设备型号: [e.g. 华为Mate 20]

**描述Bug**
清楚地描述Bug的信息。

**代码**
在这里贴上引发问题的代码，最好准确到哪一行引发问题。

**错误日志**
贴上代码的运行日志，有logcat日志的更好。打包后的应用请参考文档使用`console.setGloablLogConfig()`方法设置日志文件路径。

**截图或视频**
如果有截图或视频，请上传。也可以上传代码文件、项目文件、附近等。

**其他**
可以留下你的QQ，或者其他有用的信息。

**Comment by deuemcak** [comment]
想购买 pro，留QQ就可以了？

**Comment by holleworldabc** [comment]
1829913225
这是我i的QQ

**Comment by deuemcak** [comment]
已加Q

**Comment by holleworldabc** [comment]
我这边没发来呀

**Comment by deuemcak** [comment]
你加我吧，1577375306

**Comment by averyfai** [comment]
1740469818

**Comment by hyb1996** [comment]
https://pro.autojs.org

**Comment by YiJiang1990** [comment]
qq 275324310

**Comment by hyb1996** [comment]
这里留QQ谨防咋骗，请到官网购买。
