### ISSUE TITLE
[BUG] ODroid N2无法登录7.0.4

### ISSUE THREAD

**Issue by ksmaze** [hyb1996/Auto.js-Pro-Feedbacks#33]
**版本信息**
- Auto.js Pro版本: 7.0.4-1
- Android版本: 9.0
- ROM版本:
- 设备型号: ODroid N2

**描述Bug**
登录弹出验证失败. 给予储存空间和电话权限, 但该SBC没有Wifi或者GSM网络, 只有ethernet. 

**代码**
无法登录, 没有代码

**错误日志**
logcat: https://pastebin.com/f11ia7sk
应该是这里的问题:
08-01 11:19:00.298  9388  9388 W System.err: java.lang.IllegalStateException: (context.getSystemServic…elephonyManager).deviceId must not be null

**截图或视频**
如果有截图或视频，请上传。也可以上传代码文件、项目文件、附近等。

**其他**
QQ:55775816

**Comment by hyb1996** [comment]
由于Pro 7.0不再维护，请使用Pro 8.0
